name: 'go'

on:
  release:
    types: [published, draft]

  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v3
      # Build Go binaries
      - name: 'Build Go binaries'
        uses: cloudposse/actions/go/build@0.33.0
        env:
          GO111MODULE: on
          # Architectures to build for
          GOX_OSARCH: >-
            linux/arm
            linux/386
            linux/amd64
          OUTPUT_PATH: ${{ github.workspace }}/release/${{ github.event.repository.name }}_
      # Upload artifacts for this build
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.workspace }}/release/*
      # Attach Go binaries to GitHub Release
      - name: 'Attach artifacts to GitHub Release'
        if: ${{ github.event_name == 'release' }}
        uses: cloudposse/actions/github/release-assets@0.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PATH: ${{ github.workspace }}/release/${{ github.event.repository.name }}_*
